version: 2.1

orbs:
  docker: circleci/docker@2.0.2

jobs:
  spinup:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install ruby 2.6.3
          command: |
            # rvm is available on machine
            # See https://circleci.com/docs/2.0/docker-to-machine/#pre-installed-software
            rvm install 2.6.3
            rvm use 2.6.3
            ruby -v
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run:
          name: install gems
          command: |
            gem install bundler --version '2.3.4'
            bundle _2.3.4_ config set path vendor/bundle
            bundle _2.3.4_ check || bundle _2.3.4_ install
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: start Postgres and Solr (Docker)
          command: |
            docker-compose up -d
      - docker/install-dockerize
      - run:
          name: wait for Solr server to be ready
          command: |
            dockerize -wait tcp://localhost:8983 -wait-retry-interval 2s -timeout 20s
      - run:
          name: wait for Postgres server to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -wait-retry-interval 2s -timeout 20s

workflows:
  main:
    jobs:
      - spinup
